#!/bin/sh
# Universal post-checkout launcher - save as .githooks/post-checkout
# This script detects the platform and launches the appropriate version

is_branch_checkout=$3

# Only run for branch checkouts (not file checkouts)
if [ "$is_branch_checkout" = "1" ]; then
    echo "Switched branches, updating submodules..."
    git submodule update

    # Copy to ~/texmf on windows only (on linux the soft link works
    case "$(uname -s)" in
      *MINGW*|*MSYS*)
        mkdir -p "$USERPROFILE"/texmf/tex/latex
        mkdir -p "$USERPROFILE"/texmf/fonts/truetype/LiberationMono

        cp --recursive --update ./lib/kaobook "$USERPROFILE"/texmf/tex/latex
        cp --recursive --update ./lib/fonts/LiberationMono/*.ttf "$USERPROFILE"/texmf/fonts/truetype/LiberationMono
      ;;
        *)
      ;;
    esac
fi

exit $?

