[workspace]
authors = ["Tobias Hangleiter <tobias.hangleiter@rwth-aachen.de>"]
channels = ["conda-forge"]
name = "thesis"
platforms = ["linux-64", "win-64"]
version = "0.1.0"
requires-pixi = ">=0.43"

[tasks]
clean_all = "rm -rf build/"

[target.linux-64.tasks.clean]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r linux.latexmkrc -C {{ file }}"
[target.linux-64.tasks.build]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r linux.latexmkrc -pv {{ file }}"
[target.linux-64.tasks.watch]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r linux.latexmkrc -pvc {{ file }}"

[target.win-64.tasks.clean]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r windows.latexmkrc -C {{ file }}"
[target.win-64.tasks.build]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r windows.latexmkrc -pv {{ file }}"
[target.win-64.tasks.watch]
args = [
    { "arg" = "file", "default" = "main" }
]
cmd = "latexmk -r windows.latexmkrc -pvc {{ file }}"

[dependencies]
python = ">=3.14.3,<3.15"

[pypi-dependencies]
latexminted = ">=0.7.1, <0.8"
